/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-container": "#a4f4bf",
        "surface": "#f8f9ff",
        "primary-container": "#0f3d2a",
        "error": "#ba1a1a",
        "background": "#f8f9ff",
        "on-tertiary-fixed": "#001d31",
        "on-surface": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed-dim": "#88d7a5",
        "on-tertiary-fixed-variant": "#004b73",
        "on-secondary-fixed": "#002110",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#a2d1b6",
        "tertiary": "#002339",
        "surface-variant": "#d3e4fe",
        "primary-fixed-dim": "#a2d1b6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#217248",
        "on-secondary-fixed-variant": "#00522f",
        "on-primary-container": "#7ba88f",
        "on-tertiary-container": "#45a6eb",
        "tertiary-container": "#003959",
        "on-background": "#0b1c30",
        "on-primary-fixed-variant": "#234f3b",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed": "#cce5ff",
        "on-primary-fixed": "#002113",
        "tertiary-fixed-dim": "#93ccff",
        "surface-container": "#e5eeff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#a4f4bf",
        "outline-variant": "#c1c8c1",
        "primary-fixed": "#bdedd2",
        "outline": "#717973",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "inverse-surface": "#213145",
        "primary": "#002617",
        "on-error": "#ffffff",
        "surface-tint": "#3b6751",
        "on-surface-variant": "#414943",
        "secondary": "#186c42",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        margin: "1rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        "editorial": ["Newsreader", "Georgia", "serif"],
        "ui": ["'Plus Jakarta Sans'", "Manrope", "sans-serif"],
        "sans-refined": ["'Plus Jakarta Sans'", "sans-serif"],
        "space-grotesk": ["'Space Grotesk'", "sans-serif"],
        "space": ["'Space Grotesk'", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "data-badge": ["'JetBrains Mono'", "monospace"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "data-metric": ["'JetBrains Mono'", "monospace"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "data-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "data-metric": ["18px", { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
